version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          key: hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps

      - restore_cache:
          keys:
            - test-build-{{ arch }}-{{ .Branch }}
      - run: mix test
      - save_cache:
          key: test-build-{{ arch }}-{{ .Branch }}
          paths:
            - _build/test

      # dialyxir bug with protocols
      # https://github.com/jeremyjh/dialyxir/issues/258
      # - restore_cache:
      #     keys:
      #       - dialyzer-plt-{{ arch }}-{{ .Branch }}
      # - run: mix dialyzer --halt-exit-status
      # - save_cache:
      #     key: dialyzer-plt-{{ arch }}-{{ .Branch }}
      #     paths:
      #       - _build/dev


      - run: MIX_ENV=test mix coveralls.circle
