name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test-elixir:
    runs-on: ubuntu-latest
    name: Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [22.x, 23.x, 24.x]
        elixir: [1.11.x, 1.12.x, 1.13.x]

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: erlef/setup-elixir@v1.11
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            deps
            _build/dev
            _build/test
          key: elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Test
        env:
          CI: true
          BINANCE_API_KEY: ./secrets/ci/binance_api_key
          BINANCE_API_SECRET: ./secrets/ci/binance_api_secret
          BITMEX_API_KEY: ./secrets/ci/bitmex_api_key
          BITMEX_API_SECRET: ./secrets/ci/bitmex_api_secret
          GDAX_API_KEY: ./secrets/ci/gdax_api_key
          GDAX_API_PASSPHRASE: ./secrets/ci/gdax_api_passphrase
          GDAX_API_SECRET: ./secrets/ci/gdax_api_secret
          OKEX_API_KEY: ./secrets/ci/okex_api_key
          OKEX_API_PASSPHRASE: ./secrets/ci/okex_api_passphrase
          OKEX_API_SECRET: ./secrets/ci/okex_api_secret
          DERIBIT_CLIENT_ID: ./secrets/ci/deribit_client_id
          DERIBIT_CLIENT_SECRET: ./secrets/ci/deribit_client_secret
          FTX_API_KEY: ./secrets/ci/ftx_api_key
          FTX_API_SECRET: ./secrets/ci/ftx_api_secret
          DELTA_EXCHANGE_API_KEY: ./secrets/ci/delta_exchange_api_key
          DELTA_EXCHANGE_API_SECRET: ./secrets/ci/delta_exchange_api_secret
        run: |
          mix tai.gen.migration
          mix test

      - uses: actions/upload-artifact@v2
        with:
          name: log artifacts
          path: |
            apps/tai/log
            apps/examples/log

      - name: Dialyzer
        run: mix dialyzer
